# NOTE: This workflow requires that the current repo have a branch 'gh-pages' to hold the github pages source

name: allure-report
description: Performs a test deployment of Allure Report with history

on:
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
    # Checkout del código fuente (rama actual que lanza el workflow)
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install pytest pytest-html allure-pytest

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest --alluredir=allure-results -v

  allure:
    name: Generate Allure Report
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get Allure history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from repo
        uses: ./
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history